<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RefJnsIjinSeeder extends Seeder
{
    public function run(): void
    {
        // Kosongkan tabel dulu (DEV only)
        DB::table('ref_jns_ijin')->truncate();

        DB::table('ref_jns_ijin')->insert([
            [
                'jns_ijin' => '003',
                'nama_jns_ijin' => 'Pressure Vessel',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 3,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '005',
                'nama_jns_ijin' => 'Project',
                'kode' => 'PR',
                'tipe' => 'pr',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 0,
                'bidang' => 1,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '006',
                'nama_jns_ijin' => 'Surat Instruksi Kerja',
                'kode' => 'SIK',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '007',
                'nama_jns_ijin' => 'Inspection and Test Plan',
                'kode' => 'ITP',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 2,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '008',
                'nama_jns_ijin' => 'Heat Exchanger (Air Cooler Exchanger)',
                'kode' => 'HE',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 3,
                'aktif' => 1,
                'order_index' => 1,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '009',
                'nama_jns_ijin' => 'Heat Exchanger (Shell & Tube)',
                'kode' => 'HE',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 3,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '010',
                'nama_jns_ijin' => 'Pressure Safety Valve',
                'kode' => 'SV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 4,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '011',
                'nama_jns_ijin' => 'Pressure Relief Valve',
                'kode' => 'SV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 4,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '012',
                'nama_jns_ijin' => 'Breather Valve',
                'kode' => 'SV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 4,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '013',
                'nama_jns_ijin' => 'Storage Tank Rectangular',
                'kode' => 'ST',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 5,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '014',
                'nama_jns_ijin' => 'Pump',
                'kode' => 'PUMP',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 6,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '015',
                'nama_jns_ijin' => 'Compressor',
                'kode' => 'COMP',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 6,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '016',
                'nama_jns_ijin' => 'Generator',
                'kode' => 'GEN',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 7,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '017',
                'nama_jns_ijin' => 'Transformer',
                'kode' => 'TRANS',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 7,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '018',
                'nama_jns_ijin' => 'Switchgear',
                'kode' => 'SWG',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 7,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '019',
                'nama_jns_ijin' => 'MCC',
                'kode' => 'MCC',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 7,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '020',
                'nama_jns_ijin' => 'Pedestal Crane',
                'kode' => 'PDCR',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 8,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '021',
                'nama_jns_ijin' => 'Mobile Crane',
                'kode' => 'MBCR',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 8,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '022',
                'nama_jns_ijin' => 'Overhead Crane',
                'kode' => 'OVRH',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 8,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '023',
                'nama_jns_ijin' => 'G.A',
                'kode' => 'G.A',
                'tipe' => 'ga',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '024',
                'nama_jns_ijin' => 'PPJB',
                'kode' => 'ppjb',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '025',
                'nama_jns_ijin' => 'Custody Meter',
                'kode' => 'MT',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 9,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '026',
                'nama_jns_ijin' => 'Platform',
                'kode' => 'PF',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 10,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '027',
                'nama_jns_ijin' => 'FSO',
                'kode' => 'FSO',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 10,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '028',
                'nama_jns_ijin' => 'Installation Hilir',
                'kode' => 'INSLT',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 12,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '029',
                'nama_jns_ijin' => 'Carbon Steel Liquid On Shore',
                'kode' => 'CSLON',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '030',
                'nama_jns_ijin' => 'Polyethylene',
                'kode' => 'PLTHYL',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '031',
                'nama_jns_ijin' => 'Carbon Steel Liquid Off Shore',
                'kode' => 'CSLOFF',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '032',
                'nama_jns_ijin' => 'Carbon Steel Gas On Shore',
                'kode' => 'CSGON',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '033',
                'nama_jns_ijin' => 'Carbon Steel / Multi Phase Riser Gas Offshore',
                'kode' => 'CSGOFF',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '034',
                'nama_jns_ijin' => 'Storage Tank Roof',
                'kode' => 'ST',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 5,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '035',
                'nama_jns_ijin' => 'Employment Application Form',
                'kode' => 'EAF',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '036',
                'nama_jns_ijin' => 'Pemeriksaan Keselamatan Peralatan',
                'kode' => 'PKP',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '037',
                'nama_jns_ijin' => 'CHECK LIST DOCUMENT TENDER',
                'kode' => 'CLDOCTEND',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '038',
                'nama_jns_ijin' => 'Profile Client',
                'kode' => 'CLIENT',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 9,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '039',
                'nama_jns_ijin' => 'PSV-COI',
                'kode' => 'PSV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '040',
                'nama_jns_ijin' => 'PSV-P&ID',
                'kode' => 'PSV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 1,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '041',
                'nama_jns_ijin' => 'PSV-DATA SHEET',
                'kode' => 'PSV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 2,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '042',
                'nama_jns_ijin' => 'PV-COVER',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 1,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '043',
                'nama_jns_ijin' => 'PV-COI',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 2,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '044',
                'nama_jns_ijin' => 'PV-EXISTING COI/SKPP',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 3,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '045',
                'nama_jns_ijin' => 'PV-FORM U-1',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 4,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '046',
                'nama_jns_ijin' => 'PV-CHECK LIST',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 5,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '047',
                'nama_jns_ijin' => 'PV-WALL THICKNESS',
                'kode' => 'PV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 6,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '048',
                'nama_jns_ijin' => 'Lifting Gear',
                'kode' => 'LGI',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 8,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '049',
                'nama_jns_ijin' => 'Non Destructive Test',
                'kode' => 'NDT',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 0,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '050',
                'nama_jns_ijin' => 'Instalation SPBU',
                'kode' => 'INSLTSPBU',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 12,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '051',
                'nama_jns_ijin' => 'Installation Hulu',
                'kode' => 'INSLTHILIR',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 12,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '052',
                'nama_jns_ijin' => 'Installation Kilang',
                'kode' => 'INSLTKILAN',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 12,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '053',
                'nama_jns_ijin' => 'Pemeriksaan Keselamatan Instalasi Umum',
                'kode' => 'PKIU',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '054',
                'nama_jns_ijin' => 'Pemeriksaan Keselamatan Pipa Penyalur',
                'kode' => 'PKPP',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '055',
                'nama_jns_ijin' => 'Pemeriksaan Keselamatan Gabungan',
                'kode' => 'PKG',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '056',
                'nama_jns_ijin' => 'Persetujuan Layak Operasi Instalasi Umum',
                'kode' => 'PLOI',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '057',
                'nama_jns_ijin' => 'Surat Persetujuan Layak Operasi Instalasi Umum',
                'kode' => 'SPIU',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '058',
                'nama_jns_ijin' => 'SUrat Persetujuan Layak Operasi Pipa Penyalur',
                'kode' => 'SPPP',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '059',
                'nama_jns_ijin' => 'Surat Instruksi Kerja Market',
                'kode' => 'SIKM',
                'tipe' => 'doc',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 2,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '060',
                'nama_jns_ijin' => 'Installation SPBU',
                'kode' => 'INSLSPBU',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 12,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '061',
                'nama_jns_ijin' => 'Installation RIG',
                'kode' => 'RIG',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 13,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '062',
                'nama_jns_ijin' => 'Boiler',
                'kode' => 'BL',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 14,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '063',
                'nama_jns_ijin' => 'Storage Tank Horizontal',
                'kode' => 'ST',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 5,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '064',
                'nama_jns_ijin' => 'Turbin Meter',
                'kode' => 'TM',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 9,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '065',
                'nama_jns_ijin' => 'Tangki Ukur Terapong',
                'kode' => 'TUT',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 9,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '066',
                'nama_jns_ijin' => 'Trunkline',
                'kode' => 'TR',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '067',
                'nama_jns_ijin' => 'Flowline',
                'kode' => 'FL',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 11,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '068',
                'nama_jns_ijin' => 'UPS',
                'kode' => 'UPS',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 7,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            [
                'jns_ijin' => '069',
                'nama_jns_ijin' => 'Surge Relief Valve',
                'kode' => 'SV',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 4,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
            // … (POLA SAMA, lanjutkan data lain)
            [
                'jns_ijin' => '070',
                'nama_jns_ijin' => 'Lighting Protection (Depnaker)',
                'kode' => 'LP',
                'tipe' => 'unit',
                'masa_tahun' => null,
                'masa_bulan' => 0,
                'retribusi' => 1,
                'bidang' => 15,
                'aktif' => 1,
                'order_index' => 0,
                'oss' => 0,
            ],
        ]);
    }
}
